// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/stats/stats.proto

package stats // import "github.com/statistico/statistico-data/internal/proto/stats"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FixtureRequest struct {
	FixtureId            uint64   `protobuf:"varint,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixtureRequest) Reset()         { *m = FixtureRequest{} }
func (m *FixtureRequest) String() string { return proto.CompactTextString(m) }
func (*FixtureRequest) ProtoMessage()    {}
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{0}
}
func (m *FixtureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureRequest.Unmarshal(m, b)
}
func (m *FixtureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureRequest.Marshal(b, m, deterministic)
}
func (dst *FixtureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureRequest.Merge(dst, src)
}
func (m *FixtureRequest) XXX_Size() int {
	return xxx_messageInfo_FixtureRequest.Size(m)
}
func (m *FixtureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureRequest proto.InternalMessageInfo

func (m *FixtureRequest) GetFixtureId() uint64 {
	if m != nil {
		return m.FixtureId
	}
	return 0
}

type StatsResponse struct {
	HomeTeam             []*PlayerStats `protobuf:"bytes,1,rep,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             []*PlayerStats `protobuf:"bytes,2,rep,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{1}
}
func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (dst *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(dst, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetHomeTeam() []*PlayerStats {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *StatsResponse) GetAwayTeam() []*PlayerStats {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

type LineupResponse struct {
	HomeTeam             *Lineup  `protobuf:"bytes,1,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             *Lineup  `protobuf:"bytes,2,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineupResponse) Reset()         { *m = LineupResponse{} }
func (m *LineupResponse) String() string { return proto.CompactTextString(m) }
func (*LineupResponse) ProtoMessage()    {}
func (*LineupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{2}
}
func (m *LineupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineupResponse.Unmarshal(m, b)
}
func (m *LineupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineupResponse.Marshal(b, m, deterministic)
}
func (dst *LineupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineupResponse.Merge(dst, src)
}
func (m *LineupResponse) XXX_Size() int {
	return xxx_messageInfo_LineupResponse.Size(m)
}
func (m *LineupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LineupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LineupResponse proto.InternalMessageInfo

func (m *LineupResponse) GetHomeTeam() *Lineup {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *LineupResponse) GetAwayTeam() *Lineup {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

type PlayerStats struct {
	PlayerId             uint64               `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ShotsTotal           *wrappers.Int32Value `protobuf:"bytes,2,opt,name=shots_total,json=shotsTotal,proto3" json:"shots_total,omitempty"`
	ShotsOnGoal          *wrappers.Int32Value `protobuf:"bytes,3,opt,name=shots_on_goal,json=shotsOnGoal,proto3" json:"shots_on_goal,omitempty"`
	GoalsScored          *wrappers.Int32Value `protobuf:"bytes,4,opt,name=goals_scored,json=goalsScored,proto3" json:"goals_scored,omitempty"`
	GoalsConceded        *wrappers.Int32Value `protobuf:"bytes,5,opt,name=goals_conceded,json=goalsConceded,proto3" json:"goals_conceded,omitempty"`
	Assists              *wrappers.Int32Value `protobuf:"bytes,6,opt,name=assists,proto3" json:"assists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{3}
}
func (m *PlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStats.Unmarshal(m, b)
}
func (m *PlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStats.Marshal(b, m, deterministic)
}
func (dst *PlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStats.Merge(dst, src)
}
func (m *PlayerStats) XXX_Size() int {
	return xxx_messageInfo_PlayerStats.Size(m)
}
func (m *PlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStats proto.InternalMessageInfo

func (m *PlayerStats) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerStats) GetShotsTotal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsTotal
	}
	return nil
}

func (m *PlayerStats) GetShotsOnGoal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsOnGoal
	}
	return nil
}

func (m *PlayerStats) GetGoalsScored() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsScored
	}
	return nil
}

func (m *PlayerStats) GetGoalsConceded() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsConceded
	}
	return nil
}

func (m *PlayerStats) GetAssists() *wrappers.Int32Value {
	if m != nil {
		return m.Assists
	}
	return nil
}

type Lineup struct {
	Start                []*LineupPlayer `protobuf:"bytes,1,rep,name=start,proto3" json:"start,omitempty"`
	Bench                []*LineupPlayer `protobuf:"bytes,2,rep,name=bench,proto3" json:"bench,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Lineup) Reset()         { *m = Lineup{} }
func (m *Lineup) String() string { return proto.CompactTextString(m) }
func (*Lineup) ProtoMessage()    {}
func (*Lineup) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{4}
}
func (m *Lineup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lineup.Unmarshal(m, b)
}
func (m *Lineup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lineup.Marshal(b, m, deterministic)
}
func (dst *Lineup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lineup.Merge(dst, src)
}
func (m *Lineup) XXX_Size() int {
	return xxx_messageInfo_Lineup.Size(m)
}
func (m *Lineup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lineup.DiscardUnknown(m)
}

var xxx_messageInfo_Lineup proto.InternalMessageInfo

func (m *Lineup) GetStart() []*LineupPlayer {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Lineup) GetBench() []*LineupPlayer {
	if m != nil {
		return m.Bench
	}
	return nil
}

type LineupPlayer struct {
	PlayerId             uint64               `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position             string               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	FormationPosition    *wrappers.Int32Value `protobuf:"bytes,3,opt,name=formation_position,json=formationPosition,proto3" json:"formation_position,omitempty"`
	IsSubstitute         bool                 `protobuf:"varint,4,opt,name=is_substitute,json=isSubstitute,proto3" json:"is_substitute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LineupPlayer) Reset()         { *m = LineupPlayer{} }
func (m *LineupPlayer) String() string { return proto.CompactTextString(m) }
func (*LineupPlayer) ProtoMessage()    {}
func (*LineupPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_7aa230d471821357, []int{5}
}
func (m *LineupPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineupPlayer.Unmarshal(m, b)
}
func (m *LineupPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineupPlayer.Marshal(b, m, deterministic)
}
func (dst *LineupPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineupPlayer.Merge(dst, src)
}
func (m *LineupPlayer) XXX_Size() int {
	return xxx_messageInfo_LineupPlayer.Size(m)
}
func (m *LineupPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_LineupPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_LineupPlayer proto.InternalMessageInfo

func (m *LineupPlayer) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LineupPlayer) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *LineupPlayer) GetFormationPosition() *wrappers.Int32Value {
	if m != nil {
		return m.FormationPosition
	}
	return nil
}

func (m *LineupPlayer) GetIsSubstitute() bool {
	if m != nil {
		return m.IsSubstitute
	}
	return false
}

func init() {
	proto.RegisterType((*FixtureRequest)(nil), "stats.FixtureRequest")
	proto.RegisterType((*StatsResponse)(nil), "stats.StatsResponse")
	proto.RegisterType((*LineupResponse)(nil), "stats.LineupResponse")
	proto.RegisterType((*PlayerStats)(nil), "stats.PlayerStats")
	proto.RegisterType((*Lineup)(nil), "stats.Lineup")
	proto.RegisterType((*LineupPlayer)(nil), "stats.LineupPlayer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	GetLineUpForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*LineupResponse, error)
}

type statsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatsServiceClient(cc *grpc.ClientConn) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/stats.StatsService/GetPlayerStatsForFixture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetLineUpForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*LineupResponse, error) {
	out := new(LineupResponse)
	err := c.cc.Invoke(ctx, "/stats.StatsService/GetLineUpForFixture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
type StatsServiceServer interface {
	GetPlayerStatsForFixture(context.Context, *FixtureRequest) (*StatsResponse, error)
	GetLineUpForFixture(context.Context, *FixtureRequest) (*LineupResponse, error)
}

func RegisterStatsServiceServer(s *grpc.Server, srv StatsServiceServer) {
	s.RegisterService(&_StatsService_serviceDesc, srv)
}

func _StatsService_GetPlayerStatsForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPlayerStatsForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.StatsService/GetPlayerStatsForFixture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPlayerStatsForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetLineUpForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetLineUpForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.StatsService/GetLineUpForFixture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetLineUpForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerStatsForFixture",
			Handler:    _StatsService_GetPlayerStatsForFixture_Handler,
		},
		{
			MethodName: "GetLineUpForFixture",
			Handler:    _StatsService_GetLineUpForFixture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/stats/stats.proto",
}

func init() {
	proto.RegisterFile("internal/proto/stats/stats.proto", fileDescriptor_stats_7aa230d471821357)
}

var fileDescriptor_stats_7aa230d471821357 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0xcd, 0x7e, 0xd4, 0xf6, 0xf4, 0x03, 0x9c, 0x75, 0x21, 0x74, 0x51, 0x4a, 0xbc, 0xa9,
	0x0b, 0x26, 0xd0, 0xc5, 0x1b, 0x59, 0x14, 0x56, 0xdc, 0x52, 0x11, 0x5c, 0xd2, 0xd5, 0x0b, 0x2f,
	0x0c, 0xd3, 0xe4, 0xb4, 0x1d, 0x48, 0x33, 0xd9, 0xcc, 0x89, 0xeb, 0xbe, 0x8d, 0x8f, 0xe1, 0x03,
	0xf9, 0x20, 0x92, 0x99, 0x34, 0xdb, 0x40, 0xb5, 0x7b, 0x53, 0x7a, 0x0e, 0xbf, 0xff, 0xff, 0x84,
	0xf3, 0x31, 0x30, 0x10, 0x09, 0x61, 0x96, 0xf0, 0xd8, 0x4b, 0x33, 0x49, 0xd2, 0x53, 0xc4, 0x49,
	0x99, 0x5f, 0x57, 0x67, 0xd8, 0xa1, 0x0e, 0xfa, 0xcf, 0x17, 0x52, 0x2e, 0x62, 0x34, 0xd8, 0x2c,
	0x9f, 0x7b, 0xb7, 0x19, 0x4f, 0x53, 0xcc, 0x4a, 0xcc, 0xf1, 0xa0, 0x77, 0x29, 0x7e, 0x52, 0x9e,
	0xa1, 0x8f, 0x37, 0x39, 0x2a, 0x62, 0xcf, 0x00, 0xe6, 0x26, 0x13, 0x88, 0xc8, 0xb6, 0x06, 0xd6,
	0xf0, 0xc0, 0x6f, 0x95, 0x99, 0x49, 0xe4, 0xdc, 0x40, 0x77, 0x5a, 0x38, 0xfb, 0xa8, 0x52, 0x99,
	0x28, 0x64, 0x1e, 0xb4, 0x96, 0x72, 0x85, 0x01, 0x21, 0x5f, 0xd9, 0xd6, 0x60, 0x7f, 0xd8, 0x1e,
	0x31, 0xd7, 0x7c, 0xc9, 0x55, 0xcc, 0xef, 0x30, 0x33, 0x78, 0xb3, 0x80, 0xae, 0x91, 0xaf, 0x0a,
	0x01, 0xbf, 0xe5, 0x77, 0x46, 0xb0, 0xf7, 0x6f, 0x41, 0x01, 0x15, 0x02, 0x67, 0x09, 0xbd, 0x4f,
	0x22, 0xc1, 0x3c, 0xad, 0x6a, 0x9e, 0xd6, 0x6b, 0x5a, 0xc3, 0xf6, 0xa8, 0x5b, 0x5a, 0x94, 0xe4,
	0x7d, 0xb9, 0xd3, 0x7a, 0xb9, 0x6d, 0x6c, 0x55, 0xe9, 0xcf, 0x1e, 0xb4, 0x37, 0xbe, 0x81, 0x9d,
	0x40, 0x2b, 0xd5, 0xe1, 0x7d, 0x2b, 0x9a, 0x26, 0x31, 0x89, 0xd8, 0x39, 0xb4, 0xd5, 0x52, 0x92,
	0x0a, 0x48, 0x12, 0x8f, 0x4b, 0xeb, 0x13, 0xd7, 0x34, 0xdc, 0x5d, 0x37, 0xdc, 0x9d, 0x24, 0x74,
	0x36, 0xfa, 0xca, 0xe3, 0x1c, 0x7d, 0xd0, 0xfc, 0x75, 0x81, 0xb3, 0x77, 0xd0, 0x35, 0x6a, 0x99,
	0x04, 0x0b, 0xc9, 0x63, 0x7b, 0x7f, 0xb7, 0xde, 0xd4, 0xfb, 0x9c, 0x8c, 0x25, 0x8f, 0xd9, 0x5b,
	0xe8, 0x14, 0x3a, 0x15, 0xa8, 0x50, 0x66, 0x18, 0xd9, 0x07, 0x0f, 0xd0, 0x6b, 0xc1, 0x54, 0xf3,
	0xec, 0x02, 0x7a, 0x46, 0x1f, 0xca, 0x24, 0xc4, 0x08, 0x23, 0xfb, 0x70, 0xb7, 0x43, 0x57, 0x4b,
	0xde, 0x97, 0x0a, 0xf6, 0x1a, 0x1e, 0x73, 0xa5, 0x84, 0x22, 0x65, 0x37, 0x76, 0x8b, 0xd7, 0xac,
	0xf3, 0x1d, 0x1a, 0xa6, 0xf5, 0xec, 0x25, 0x14, 0x7b, 0x9a, 0x51, 0xb9, 0x38, 0x47, 0xb5, 0xc1,
	0x98, 0x49, 0xf8, 0x86, 0x28, 0xd0, 0x19, 0x26, 0xe1, 0xb2, 0x5c, 0x99, 0xed, 0xa8, 0x26, 0x9c,
	0xdf, 0x16, 0x74, 0x36, 0xf3, 0xff, 0x9f, 0x63, 0x1f, 0x9a, 0xa9, 0x54, 0x82, 0x84, 0x4c, 0xf4,
	0x10, 0x5b, 0x7e, 0x15, 0xb3, 0x8f, 0xc0, 0xe6, 0x32, 0x5b, 0xf1, 0x22, 0x08, 0x2a, 0xea, 0x01,
	0xa3, 0x7a, 0x52, 0xc9, 0xae, 0xd6, 0x5e, 0x2f, 0xa0, 0x2b, 0x54, 0xa0, 0xf2, 0x99, 0x22, 0x41,
	0x39, 0xa1, 0x9e, 0x58, 0xd3, 0xef, 0x08, 0x35, 0xad, 0x72, 0xa3, 0x5f, 0x16, 0x74, 0xf4, 0xee,
	0x4d, 0x31, 0xfb, 0x21, 0x42, 0x64, 0x13, 0xb0, 0xc7, 0x48, 0x1b, 0x4b, 0x79, 0x29, 0xb3, 0xf2,
	0x62, 0xd9, 0x71, 0xd9, 0x83, 0xfa, 0x05, 0xf7, 0x9f, 0x96, 0xe9, 0xda, 0x9d, 0x3a, 0x8f, 0xd8,
	0x07, 0x38, 0x1a, 0x23, 0x15, 0x8d, 0xf9, 0x92, 0xee, 0x76, 0x39, 0xae, 0x1f, 0x49, 0x65, 0x73,
	0x71, 0xfe, 0xed, 0xcd, 0x42, 0xd0, 0x32, 0x9f, 0xb9, 0xa1, 0x5c, 0xe9, 0x37, 0x47, 0x28, 0x12,
	0xa1, 0xdc, 0xf8, 0xfb, 0x2a, 0xe2, 0xc4, 0xbd, 0x6d, 0x6f, 0xd4, 0xac, 0xa1, 0x83, 0xb3, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x6a, 0x58, 0xda, 0xc2, 0x04, 0x00, 0x00,
}
