// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/stats/stats.proto

package stats // import "github.com/statistico/statistico-data/internal/proto/stats"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FixtureRequest struct {
	FixtureId            uint64   `protobuf:"varint,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixtureRequest) Reset()         { *m = FixtureRequest{} }
func (m *FixtureRequest) String() string { return proto.CompactTextString(m) }
func (*FixtureRequest) ProtoMessage()    {}
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_b960c4b59b86842c, []int{0}
}
func (m *FixtureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureRequest.Unmarshal(m, b)
}
func (m *FixtureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureRequest.Marshal(b, m, deterministic)
}
func (dst *FixtureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureRequest.Merge(dst, src)
}
func (m *FixtureRequest) XXX_Size() int {
	return xxx_messageInfo_FixtureRequest.Size(m)
}
func (m *FixtureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureRequest proto.InternalMessageInfo

func (m *FixtureRequest) GetFixtureId() uint64 {
	if m != nil {
		return m.FixtureId
	}
	return 0
}

type FixtureResponse struct {
	HomeTeam             []*PlayerStats `protobuf:"bytes,1,rep,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             []*PlayerStats `protobuf:"bytes,2,rep,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FixtureResponse) Reset()         { *m = FixtureResponse{} }
func (m *FixtureResponse) String() string { return proto.CompactTextString(m) }
func (*FixtureResponse) ProtoMessage()    {}
func (*FixtureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_b960c4b59b86842c, []int{1}
}
func (m *FixtureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureResponse.Unmarshal(m, b)
}
func (m *FixtureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureResponse.Marshal(b, m, deterministic)
}
func (dst *FixtureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureResponse.Merge(dst, src)
}
func (m *FixtureResponse) XXX_Size() int {
	return xxx_messageInfo_FixtureResponse.Size(m)
}
func (m *FixtureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureResponse proto.InternalMessageInfo

func (m *FixtureResponse) GetHomeTeam() []*PlayerStats {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *FixtureResponse) GetAwayTeam() []*PlayerStats {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

type PlayerStats struct {
	PlayerId             uint64               `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ShotsTotal           *wrappers.Int32Value `protobuf:"bytes,2,opt,name=shots_total,json=shotsTotal,proto3" json:"shots_total,omitempty"`
	ShotsOnGoal          *wrappers.Int32Value `protobuf:"bytes,3,opt,name=shots_on_goal,json=shotsOnGoal,proto3" json:"shots_on_goal,omitempty"`
	GoalsScored          *wrappers.Int32Value `protobuf:"bytes,4,opt,name=goals_scored,json=goalsScored,proto3" json:"goals_scored,omitempty"`
	GoalsConceded        *wrappers.Int32Value `protobuf:"bytes,5,opt,name=goals_conceded,json=goalsConceded,proto3" json:"goals_conceded,omitempty"`
	Assists              *wrappers.Int32Value `protobuf:"bytes,6,opt,name=assists,proto3" json:"assists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_stats_b960c4b59b86842c, []int{2}
}
func (m *PlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStats.Unmarshal(m, b)
}
func (m *PlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStats.Marshal(b, m, deterministic)
}
func (dst *PlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStats.Merge(dst, src)
}
func (m *PlayerStats) XXX_Size() int {
	return xxx_messageInfo_PlayerStats.Size(m)
}
func (m *PlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStats proto.InternalMessageInfo

func (m *PlayerStats) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerStats) GetShotsTotal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsTotal
	}
	return nil
}

func (m *PlayerStats) GetShotsOnGoal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsOnGoal
	}
	return nil
}

func (m *PlayerStats) GetGoalsScored() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsScored
	}
	return nil
}

func (m *PlayerStats) GetGoalsConceded() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsConceded
	}
	return nil
}

func (m *PlayerStats) GetAssists() *wrappers.Int32Value {
	if m != nil {
		return m.Assists
	}
	return nil
}

func init() {
	proto.RegisterType((*FixtureRequest)(nil), "stats.FixtureRequest")
	proto.RegisterType((*FixtureResponse)(nil), "stats.FixtureResponse")
	proto.RegisterType((*PlayerStats)(nil), "stats.PlayerStats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*FixtureResponse, error)
}

type statsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatsServiceClient(cc *grpc.ClientConn) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*FixtureResponse, error) {
	out := new(FixtureResponse)
	err := c.cc.Invoke(ctx, "/stats.StatsService/GetPlayerStatsForFixture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
type StatsServiceServer interface {
	GetPlayerStatsForFixture(context.Context, *FixtureRequest) (*FixtureResponse, error)
}

func RegisterStatsServiceServer(s *grpc.Server, srv StatsServiceServer) {
	s.RegisterService(&_StatsService_serviceDesc, srv)
}

func _StatsService_GetPlayerStatsForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPlayerStatsForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.StatsService/GetPlayerStatsForFixture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPlayerStatsForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerStatsForFixture",
			Handler:    _StatsService_GetPlayerStatsForFixture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/stats/stats.proto",
}

func init() {
	proto.RegisterFile("internal/proto/stats/stats.proto", fileDescriptor_stats_b960c4b59b86842c)
}

var fileDescriptor_stats_b960c4b59b86842c = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xbd, 0xeb, 0x0f, 0x7b, 0x93, 0xb6, 0xc2, 0x82, 0xb2, 0xb4, 0x28, 0x21, 0x4f, 0xf7,
	0x62, 0x02, 0x29, 0xbe, 0x48, 0x51, 0xa8, 0xd0, 0x72, 0xf8, 0xa0, 0xe4, 0x8a, 0x0f, 0xfa, 0x10,
	0xf6, 0x92, 0x69, 0x6e, 0x21, 0xc9, 0xc4, 0xdd, 0x89, 0xb5, 0xff, 0xaf, 0x7f, 0x88, 0x64, 0x37,
	0xd5, 0x53, 0x94, 0xeb, 0x4b, 0xd8, 0xf9, 0xe6, 0xf3, 0x49, 0x96, 0x99, 0x81, 0x50, 0xb7, 0x8c,
	0xa6, 0x55, 0x75, 0xd2, 0x19, 0x62, 0x4a, 0x2c, 0x2b, 0xb6, 0xfe, 0x19, 0xbb, 0x44, 0xec, 0xb9,
	0xe2, 0xe4, 0x45, 0x45, 0x54, 0xd5, 0xe8, 0xb1, 0x55, 0x7f, 0x93, 0xdc, 0x1a, 0xd5, 0x75, 0x68,
	0x46, 0x2c, 0x4a, 0xe0, 0xf8, 0x52, 0x7f, 0xe7, 0xde, 0x60, 0x86, 0x5f, 0x7b, 0xb4, 0x2c, 0x9e,
	0x03, 0xdc, 0xf8, 0x24, 0xd7, 0xa5, 0x9c, 0x84, 0x93, 0xf9, 0x6e, 0x36, 0x1b, 0x93, 0x45, 0x19,
	0x59, 0x78, 0xf2, 0x4b, 0xb0, 0x1d, 0xb5, 0x16, 0x45, 0x02, 0xb3, 0x35, 0x35, 0x98, 0x33, 0xaa,
	0x46, 0x4e, 0xc2, 0x9d, 0x79, 0x90, 0x8a, 0xd8, 0xdf, 0xe5, 0x63, 0xad, 0xee, 0xd0, 0x2c, 0x87,
	0x73, 0x76, 0x30, 0x40, 0xd7, 0xa8, 0x9a, 0x41, 0x50, 0xb7, 0xea, 0xce, 0x0b, 0xd3, 0xff, 0x0b,
	0x03, 0x34, 0x08, 0xd1, 0x8f, 0x29, 0x04, 0x1b, 0x6f, 0xc4, 0x29, 0xcc, 0x3a, 0x57, 0xfe, 0xbe,
	0xe2, 0x81, 0x0f, 0x16, 0xa5, 0x38, 0x87, 0xc0, 0xae, 0x89, 0x6d, 0xce, 0xc4, 0xaa, 0x96, 0xd3,
	0x70, 0x32, 0x0f, 0xd2, 0xd3, 0xd8, 0x37, 0x22, 0xbe, 0x6f, 0x44, 0xbc, 0x68, 0xf9, 0x2c, 0xfd,
	0xa4, 0xea, 0x1e, 0x33, 0x70, 0xfc, 0xf5, 0x80, 0x8b, 0xb7, 0x70, 0xe4, 0x6d, 0x6a, 0xf3, 0x8a,
	0x54, 0x2d, 0x77, 0xb6, 0xfb, 0xfe, 0x7f, 0x1f, 0xda, 0x2b, 0x52, 0xb5, 0x78, 0x03, 0x87, 0x83,
	0x67, 0x73, 0x5b, 0x90, 0xc1, 0x52, 0xee, 0x3e, 0xc0, 0x77, 0xc2, 0xd2, 0xf1, 0xe2, 0x02, 0x8e,
	0xbd, 0x5f, 0x50, 0x5b, 0x60, 0x89, 0xa5, 0xdc, 0xdb, 0xfe, 0x85, 0x23, 0xa7, 0xbc, 0x1b, 0x0d,
	0xf1, 0x0a, 0x1e, 0x2b, 0x6b, 0xb5, 0x65, 0x2b, 0xf7, 0xb7, 0xcb, 0xf7, 0x6c, 0xfa, 0x05, 0x0e,
	0x5d, 0x7f, 0x97, 0x68, 0xbe, 0xe9, 0x02, 0xc5, 0x7b, 0x90, 0x57, 0xc8, 0x1b, 0x8d, 0xbf, 0x24,
	0x33, 0x0e, 0x5f, 0x3c, 0x1d, 0x07, 0xf6, 0xe7, 0xf6, 0x9c, 0x3c, 0xfb, 0x3b, 0xf6, 0x3b, 0x12,
	0x3d, 0xba, 0x38, 0xff, 0xfc, 0xba, 0xd2, 0xbc, 0xee, 0x57, 0x71, 0x41, 0x8d, 0x5b, 0x55, 0x6d,
	0x59, 0x17, 0xb4, 0x71, 0x7c, 0x59, 0x2a, 0x56, 0xc9, 0xbf, 0x56, 0x7b, 0xb5, 0xef, 0x8a, 0xb3,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0x46, 0x60, 0xa8, 0xf9, 0x02, 0x00, 0x00,
}
