version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statshub
    ports:
      - 5432:5432

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      NAME: "Joe"
    links:
      - postgres

  console:
    build:
      dockerfile: ./docker/console/Dockerfile
      context: .
    environment:
      SPORT_MONKS_URI: "https://soccer.sportmonks.com/api/v2.0"
      SPORT_MONKS_API_KEY: "hMNoq0c2fMjipNWEeG7IMmDF9bMNKeVoRi8lJ0qZDhg125U1IormejZKfwua"
    tty: true
    links:
      - postgres