version: "3.3"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      NAME: "Joe"

  console:
    build: ./console
    environment:
      SPORT_MONKS_URI: "https://soccer.sportmonks.com/api/v2.0"
      SPORT_MONKS_API_KEY: "hMNoq0c2fMjipNWEeG7IMmDF9bMNKeVoRi8lJ0qZDhg125U1IormejZKfwua"
    tty: true
