version: "3.5"
services:

  api:
    image: joesweeny/statshub_api:$RELEASE
    ports:
      - "80:8000"
    environment:
      NAME: "Joe"

  console:
    image: joesweeny/statshub_console:$RELEASE
    environment:
      DB_DRIVER: $DB_DRIVER
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      SPORT_MONKS_API_KEY: $SPORT_MONKS_API_KEY
    tty: true

  migrate:
    image: joesweeny/statshub_migrate:$RELEASE
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
    command: ["./bin/migrate"]