version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statshub
    ports:
      - 5432:5432

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      NAME: "Joe"
    links:
      - postgres

  console:
    build:
      dockerfile: ./docker/console/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statshub
      DB_PASSWORD: password
      DB_USER: dev
      DB_PORT: 5432
    tty: true
    links:
      - postgres

  migrate:
    build:
      dockerfile: ./docker/migrate/Dockerfile
      context: .
    environment:
      DB_HOST: postgres
      DB_USER: dev
      DB_PASSWORD: password
      DB_NAME: statshub
    links:
      - postgres
    depends_on:
      - postgres
    command: ["./bin/migrate"]

  test:
    build:
      dockerfile: ./docker/test/Dockerfile
      context: .
    volumes:
      - .:/go/src/github.com/joesweeny/statshub
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statshub
      DB_USER: dev
      DB_PORT: 5432
    links:
      - postgres
    depends_on:
      - postgres
    tty: true
