version: "3.5"
services:

  console:
    image: joesweeny/statisticodata_console:$RELEASE
    environment:
      DB_DRIVER: $DB_DRIVER
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      SPORTMONKS_API_KEY: $SPORTMONKS_API_KEY
    tty: true

  cron:
    image: joesweeny/statisticodata_cron:$RELEASE
    environment:
      DB_DRIVER: $DB_DRIVER
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      SPORTMONKS_API_KEY: $SPORTMONKS_API_KEY

  grpc:
    image: joesweeny/statisticodata_grpc:$RELEASE
    environment:
      DB_DRIVER: $DB_DRIVER
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      SPORTMONKS_API_KEY: $SPORTMONKS_API_KEY
    ports:
      - "50051:50051"
    tty: true

  migrate:
    image: joesweeny/statisticodata_migrate:$RELEASE
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
    command: ["./bin/migrate"]