version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: statistico
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistico_data
    volumes:
      - .:/opt
    ports:
      - 5432:5432
    networks:
      - statistico-football-data_default

  console: &console
    build:
      dockerfile: .docker/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statistico_data
      DB_PASSWORD: password
      DB_USER: statistico
      DB_PORT: 5432
    tty: true
    links:
      - postgres
    networks:
      - statistico-football-data_default

  migrate:
    <<: *console
    command: ["./bin/migrate"]

  statistico-football-data-grpc:
    <<: *console
    networks:
      - statistico-football-data_default
      - statistico_internal
    ports:
      - "50051:50051"
    command: ["./grpc", "--port 50051"]

  cron:
    <<: *console
    command: [ "crond", "-f", "-d", "8" ]

  test:
    build:
      dockerfile: .docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statistico_data
      DB_USER: statistico
      DB_PORT: 5432
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - statistico-football-data_default

networks:
  statistico-football-data_default:
    external: false
  statistico_internal:
    external: true