version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statshub
    ports:
      - 5432:5432

  console: &console
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statshub
      DB_PASSWORD: password
      DB_USER: dev
      DB_PORT: 5432
    tty: true
    links:
      - postgres

  cron:
    <<: *console
    command: ["crond", "-f", "-d", "8"]

  migrate:
    <<: *console
    command: ["./bin/migrate"]

  grpc:
    <<: *console
    ports:
      - "50051:50051"
    command: ["./grpc", "--port 50051"]

  test:
    build:
      dockerfile: ./docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statshub
      DB_USER: dev
      DB_PORT: 5432
    links:
      - postgres
    depends_on:
      - postgres
