// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/grpc/proto/player_stats.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerStatsResponse struct {
	HomeTeam             []*PlayerStats `protobuf:"bytes,1,rep,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             []*PlayerStats `protobuf:"bytes,2,rep,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerStatsResponse) Reset()         { *m = PlayerStatsResponse{} }
func (m *PlayerStatsResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerStatsResponse) ProtoMessage()    {}
func (*PlayerStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c09208fb57dbde0e, []int{0}
}

func (m *PlayerStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStatsResponse.Unmarshal(m, b)
}
func (m *PlayerStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStatsResponse.Marshal(b, m, deterministic)
}
func (m *PlayerStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStatsResponse.Merge(m, src)
}
func (m *PlayerStatsResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerStatsResponse.Size(m)
}
func (m *PlayerStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStatsResponse proto.InternalMessageInfo

func (m *PlayerStatsResponse) GetHomeTeam() []*PlayerStats {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *PlayerStatsResponse) GetAwayTeam() []*PlayerStats {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

type LineupResponse struct {
	HomeTeam             *Lineup  `protobuf:"bytes,1,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             *Lineup  `protobuf:"bytes,2,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineupResponse) Reset()         { *m = LineupResponse{} }
func (m *LineupResponse) String() string { return proto.CompactTextString(m) }
func (*LineupResponse) ProtoMessage()    {}
func (*LineupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c09208fb57dbde0e, []int{1}
}

func (m *LineupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineupResponse.Unmarshal(m, b)
}
func (m *LineupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineupResponse.Marshal(b, m, deterministic)
}
func (m *LineupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineupResponse.Merge(m, src)
}
func (m *LineupResponse) XXX_Size() int {
	return xxx_messageInfo_LineupResponse.Size(m)
}
func (m *LineupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LineupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LineupResponse proto.InternalMessageInfo

func (m *LineupResponse) GetHomeTeam() *Lineup {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *LineupResponse) GetAwayTeam() *Lineup {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

type PlayerStats struct {
	PlayerId             uint64               `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ShotsTotal           *wrappers.Int32Value `protobuf:"bytes,2,opt,name=shots_total,json=shotsTotal,proto3" json:"shots_total,omitempty"`
	ShotsOnGoal          *wrappers.Int32Value `protobuf:"bytes,3,opt,name=shots_on_goal,json=shotsOnGoal,proto3" json:"shots_on_goal,omitempty"`
	GoalsScored          *wrappers.Int32Value `protobuf:"bytes,4,opt,name=goals_scored,json=goalsScored,proto3" json:"goals_scored,omitempty"`
	GoalsConceded        *wrappers.Int32Value `protobuf:"bytes,5,opt,name=goals_conceded,json=goalsConceded,proto3" json:"goals_conceded,omitempty"`
	Assists              *wrappers.Int32Value `protobuf:"bytes,6,opt,name=assists,proto3" json:"assists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_c09208fb57dbde0e, []int{2}
}

func (m *PlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStats.Unmarshal(m, b)
}
func (m *PlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStats.Marshal(b, m, deterministic)
}
func (m *PlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStats.Merge(m, src)
}
func (m *PlayerStats) XXX_Size() int {
	return xxx_messageInfo_PlayerStats.Size(m)
}
func (m *PlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStats proto.InternalMessageInfo

func (m *PlayerStats) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerStats) GetShotsTotal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsTotal
	}
	return nil
}

func (m *PlayerStats) GetShotsOnGoal() *wrappers.Int32Value {
	if m != nil {
		return m.ShotsOnGoal
	}
	return nil
}

func (m *PlayerStats) GetGoalsScored() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsScored
	}
	return nil
}

func (m *PlayerStats) GetGoalsConceded() *wrappers.Int32Value {
	if m != nil {
		return m.GoalsConceded
	}
	return nil
}

func (m *PlayerStats) GetAssists() *wrappers.Int32Value {
	if m != nil {
		return m.Assists
	}
	return nil
}

type Lineup struct {
	Start                []*LineupPlayer `protobuf:"bytes,1,rep,name=start,proto3" json:"start,omitempty"`
	Bench                []*LineupPlayer `protobuf:"bytes,2,rep,name=bench,proto3" json:"bench,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Lineup) Reset()         { *m = Lineup{} }
func (m *Lineup) String() string { return proto.CompactTextString(m) }
func (*Lineup) ProtoMessage()    {}
func (*Lineup) Descriptor() ([]byte, []int) {
	return fileDescriptor_c09208fb57dbde0e, []int{3}
}

func (m *Lineup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lineup.Unmarshal(m, b)
}
func (m *Lineup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lineup.Marshal(b, m, deterministic)
}
func (m *Lineup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lineup.Merge(m, src)
}
func (m *Lineup) XXX_Size() int {
	return xxx_messageInfo_Lineup.Size(m)
}
func (m *Lineup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lineup.DiscardUnknown(m)
}

var xxx_messageInfo_Lineup proto.InternalMessageInfo

func (m *Lineup) GetStart() []*LineupPlayer {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Lineup) GetBench() []*LineupPlayer {
	if m != nil {
		return m.Bench
	}
	return nil
}

type LineupPlayer struct {
	PlayerId             uint64                `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position             string                `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	FormationPosition    *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=formation_position,json=formationPosition,proto3" json:"formation_position,omitempty"`
	IsSubstitute         bool                  `protobuf:"varint,4,opt,name=is_substitute,json=isSubstitute,proto3" json:"is_substitute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LineupPlayer) Reset()         { *m = LineupPlayer{} }
func (m *LineupPlayer) String() string { return proto.CompactTextString(m) }
func (*LineupPlayer) ProtoMessage()    {}
func (*LineupPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c09208fb57dbde0e, []int{4}
}

func (m *LineupPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineupPlayer.Unmarshal(m, b)
}
func (m *LineupPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineupPlayer.Marshal(b, m, deterministic)
}
func (m *LineupPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineupPlayer.Merge(m, src)
}
func (m *LineupPlayer) XXX_Size() int {
	return xxx_messageInfo_LineupPlayer.Size(m)
}
func (m *LineupPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_LineupPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_LineupPlayer proto.InternalMessageInfo

func (m *LineupPlayer) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LineupPlayer) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *LineupPlayer) GetFormationPosition() *wrappers.UInt32Value {
	if m != nil {
		return m.FormationPosition
	}
	return nil
}

func (m *LineupPlayer) GetIsSubstitute() bool {
	if m != nil {
		return m.IsSubstitute
	}
	return false
}

func init() {
	proto.RegisterType((*PlayerStatsResponse)(nil), "proto.PlayerStatsResponse")
	proto.RegisterType((*LineupResponse)(nil), "proto.LineupResponse")
	proto.RegisterType((*PlayerStats)(nil), "proto.PlayerStats")
	proto.RegisterType((*Lineup)(nil), "proto.Lineup")
	proto.RegisterType((*LineupPlayer)(nil), "proto.LineupPlayer")
}

func init() {
	proto.RegisterFile("internal/app/grpc/proto/player_stats.proto", fileDescriptor_c09208fb57dbde0e)
}

var fileDescriptor_c09208fb57dbde0e = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xef, 0x6a, 0x13, 0x4d,
	0x14, 0xc6, 0xdf, 0xb4, 0x4d, 0xde, 0xe4, 0x24, 0x29, 0x38, 0xa1, 0xb0, 0xa4, 0x22, 0x12, 0x41,
	0x6a, 0x3e, 0x64, 0x21, 0xc5, 0x6f, 0xa2, 0xa0, 0xd8, 0x50, 0x14, 0x5a, 0x36, 0xad, 0x1f, 0x5d,
	0x26, 0x9b, 0xd3, 0x64, 0x60, 0x33, 0x33, 0xce, 0xcc, 0x1a, 0x7b, 0x4f, 0xde, 0x80, 0xf7, 0xe3,
	0x85, 0xc8, 0xfc, 0xc9, 0xba, 0xc1, 0xd4, 0xf8, 0x29, 0xcc, 0xc9, 0xef, 0x79, 0x9e, 0x9d, 0x73,
	0xe6, 0xc0, 0x90, 0x71, 0x83, 0x8a, 0xd3, 0x3c, 0xa6, 0x52, 0xc6, 0x0b, 0x25, 0xb3, 0x58, 0x2a,
	0x61, 0x44, 0x2c, 0x73, 0x7a, 0x8f, 0x2a, 0xd5, 0x86, 0x1a, 0x3d, 0x72, 0x25, 0x52, 0x77, 0x3f,
	0xfd, 0x27, 0x0b, 0x21, 0x16, 0x39, 0x7a, 0x6e, 0x56, 0xdc, 0xc5, 0x6b, 0x45, 0xa5, 0x44, 0x15,
	0xb0, 0xfe, 0xf3, 0x87, 0x2c, 0x15, 0x7e, 0x29, 0x50, 0x6f, 0xec, 0x06, 0x6b, 0xe8, 0x5d, 0xbb,
	0x90, 0xa9, 0xcd, 0x48, 0x50, 0x4b, 0xc1, 0x35, 0x92, 0x18, 0x5a, 0x4b, 0xb1, 0xc2, 0xd4, 0x20,
	0x5d, 0x45, 0xb5, 0xa7, 0x87, 0x67, 0xed, 0x31, 0xf1, 0x8a, 0x51, 0x15, 0x6f, 0x5a, 0xe8, 0x06,
	0xe9, 0xca, 0x0a, 0xe8, 0x9a, 0xde, 0x7b, 0xc1, 0xc1, 0xc3, 0x02, 0x0b, 0x59, 0xc1, 0x60, 0x09,
	0xc7, 0x1f, 0x19, 0xc7, 0x42, 0x96, 0x99, 0xc3, 0xed, 0xcc, 0xda, 0x59, 0x7b, 0xdc, 0x0d, 0x16,
	0x81, 0xfc, 0x1d, 0x37, 0xdc, 0x8e, 0xdb, 0xc5, 0x96, 0x49, 0x3f, 0x0f, 0xa0, 0x5d, 0xf9, 0x06,
	0x72, 0x0a, 0xad, 0xd0, 0x57, 0x36, 0x77, 0x39, 0x47, 0x49, 0xd3, 0x17, 0x2e, 0xe7, 0xe4, 0x15,
	0xb4, 0xf5, 0x52, 0x18, 0x9d, 0x1a, 0x61, 0x68, 0x1e, 0xac, 0x4f, 0x47, 0xbe, 0xdb, 0xa3, 0x4d,
	0xb7, 0x47, 0x97, 0xdc, 0x9c, 0x8f, 0x3f, 0xd1, 0xbc, 0xc0, 0x04, 0x1c, 0x7f, 0x63, 0x71, 0xf2,
	0x06, 0xba, 0x5e, 0x2d, 0x78, 0xba, 0x10, 0x34, 0x8f, 0x0e, 0xf7, 0xeb, 0x7d, 0xde, 0x15, 0x9f,
	0x08, 0x9a, 0x93, 0xd7, 0xd0, 0xb1, 0x3a, 0x9d, 0xea, 0x4c, 0x28, 0x9c, 0x47, 0x47, 0xff, 0xa0,
	0x77, 0x82, 0xa9, 0xe3, 0xc9, 0x5b, 0x38, 0xf6, 0xfa, 0x4c, 0xf0, 0x0c, 0xe7, 0x38, 0x8f, 0xea,
	0xfb, 0x1d, 0xba, 0x4e, 0xf2, 0x2e, 0x28, 0xc8, 0x4b, 0xf8, 0x9f, 0x6a, 0xcd, 0xb4, 0xd1, 0x51,
	0x63, 0xbf, 0x78, 0xc3, 0x0e, 0x3e, 0x43, 0xc3, 0xb7, 0x9e, 0xbc, 0x80, 0xba, 0x36, 0x54, 0x99,
	0xf0, 0x70, 0x7a, 0x5b, 0x83, 0xf1, 0x93, 0x48, 0x3c, 0x61, 0xd1, 0x19, 0xf2, 0x6c, 0x19, 0x9e,
	0xcc, 0x6e, 0xd4, 0x11, 0x83, 0x1f, 0x35, 0xe8, 0x54, 0xeb, 0x7f, 0x9f, 0x63, 0x1f, 0x9a, 0x52,
	0x68, 0x66, 0x98, 0xe0, 0x6e, 0x88, 0xad, 0xa4, 0x3c, 0x93, 0x0f, 0x40, 0xee, 0x84, 0x5a, 0x51,
	0x7b, 0x48, 0x4b, 0xca, 0x8f, 0xea, 0xf1, 0x1f, 0x77, 0xbd, 0xad, 0x5c, 0xf6, 0x51, 0xa9, 0xbb,
	0xde, 0x98, 0x3d, 0x83, 0x2e, 0xd3, 0xa9, 0x2e, 0x66, 0xda, 0x30, 0x53, 0x18, 0x74, 0x23, 0x6b,
	0x26, 0x1d, 0xa6, 0xa7, 0x65, 0x6d, 0xfc, 0xbd, 0x06, 0xa4, 0xf2, 0x04, 0xa7, 0xa8, 0xbe, 0xb2,
	0x0c, 0xc9, 0x15, 0x44, 0x13, 0x34, 0x95, 0x3f, 0x2e, 0x84, 0xba, 0x60, 0xdf, 0x4c, 0xa1, 0x90,
	0x9c, 0x84, 0x56, 0x84, 0x73, 0xe2, 0xd7, 0xb6, 0xdf, 0xdf, 0xb1, 0x54, 0x61, 0x81, 0x06, 0xff,
	0x91, 0xf7, 0xd0, 0x9b, 0xa0, 0xb1, 0x5d, 0xba, 0x95, 0xfb, 0xbd, 0x4e, 0xb6, 0x37, 0xa6, 0xb4,
	0x99, 0x35, 0x5c, 0xfd, 0xfc, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0xe2, 0xbd, 0x9c, 0x98,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerStatsServiceClient is the client API for PlayerStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerStatsServiceClient interface {
	GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error)
	GetLineUpForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*LineupResponse, error)
}

type playerStatsServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayerStatsServiceClient(cc *grpc.ClientConn) PlayerStatsServiceClient {
	return &playerStatsServiceClient{cc}
}

func (c *playerStatsServiceClient) GetPlayerStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error) {
	out := new(PlayerStatsResponse)
	err := c.cc.Invoke(ctx, "/proto.PlayerStatsService/GetPlayerStatsForFixture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerStatsServiceClient) GetLineUpForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*LineupResponse, error) {
	out := new(LineupResponse)
	err := c.cc.Invoke(ctx, "/proto.PlayerStatsService/GetLineUpForFixture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerStatsServiceServer is the server API for PlayerStatsService service.
type PlayerStatsServiceServer interface {
	GetPlayerStatsForFixture(context.Context, *FixtureRequest) (*PlayerStatsResponse, error)
	GetLineUpForFixture(context.Context, *FixtureRequest) (*LineupResponse, error)
}

// UnimplementedPlayerStatsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerStatsServiceServer struct {
}

func (*UnimplementedPlayerStatsServiceServer) GetPlayerStatsForFixture(ctx context.Context, req *FixtureRequest) (*PlayerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStatsForFixture not implemented")
}
func (*UnimplementedPlayerStatsServiceServer) GetLineUpForFixture(ctx context.Context, req *FixtureRequest) (*LineupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLineUpForFixture not implemented")
}

func RegisterPlayerStatsServiceServer(s *grpc.Server, srv PlayerStatsServiceServer) {
	s.RegisterService(&_PlayerStatsService_serviceDesc, srv)
}

func _PlayerStatsService_GetPlayerStatsForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerStatsServiceServer).GetPlayerStatsForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlayerStatsService/GetPlayerStatsForFixture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerStatsServiceServer).GetPlayerStatsForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerStatsService_GetLineUpForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerStatsServiceServer).GetLineUpForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlayerStatsService/GetLineUpForFixture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerStatsServiceServer).GetLineUpForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerStatsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PlayerStatsService",
	HandlerType: (*PlayerStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerStatsForFixture",
			Handler:    _PlayerStatsService_GetPlayerStatsForFixture_Handler,
		},
		{
			MethodName: "GetLineUpForFixture",
			Handler:    _PlayerStatsService_GetLineUpForFixture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/grpc/proto/player_stats.proto",
}
