package main

const Competition = "competition"
const Country = "country"
const Fixture = "fixture"
const FixtureCurrentSeason = "fixture:current-season"
const Round = "round"
const RoundCurrentSeason = "round:current-season"
const Season = "season"
const Squad = "squad"
const SquadCurrentSeason = "squad:current-season"
const Team = "team"
const TeamCurrentSeason = "team:current-season"
const Venue = "venue"
const VenueCurrentSeason = "venue:current-season"
