version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20

jobs:
  build:
    working_directory: ~/go/src/github.com/statistico/statistico-data
    machine: true
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run:
          name: Build Release Image
          command: |
            docker-compose -f docker-compose.build.yml up -d --build
  test:
    working_directory: ~/go/src/github.com/statistico/statistico-data
    machine: true
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run:
          name: Test Release Image
          command: |
            docker-compose -f docker-compose.build.yml run test gotestsum -f short-verbose
  push-images:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: Push images to ECR
          command: |
            chmod +x ./.circleci/deploy/docker-push.sh && ./.circleci/deploy/docker-push.sh

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push-images:
          requires:
            - build
            - test
          filters:
            branches:
              only: master-test
          