version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/joesweeny/statshub
    machine: true
    environment:
      GOPATH: /home/circleci/go

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "3f:66:e4:bb:f0:43:80:a8:78:1f:e5:36:7b:41:34:56"

      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep

      - run:
          name: Build Release Image
          command: |
            dep ensure
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            dep ensure
            docker-compose -f docker-compose.yml run test gotestsum -f short-verbose

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan $PRODUCTION_SERVER >> ~/.ssh/known_hosts
              chmod +x ./.circleci/deploy/docker-push.sh
              ./.circleci/deploy/docker-push.sh
              chmod +x ./.circleci/deploy/docker-deploy.sh
              ./.circleci/deploy/docker-deploy.sh
            fi
