version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
      environment:
        GOROOT: ""
        GOPATH: "${HOME}/.go_project"
        PATH: "${GOPATH}/bin:${PATH}"
        BUILD_PATH: "${GOPATH}/src/github.com/joesweeny/stats-hub"

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mkdir -p ~/.go_project/src/github.com/joesweeny
            ln -s ${HOME}/stats-hub ${BUILD_PATH}
            sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
            sudo apt-get install glide

      - run:
          name: Build Release Image
          command: |
            glide install
            docker-compose -f docker-compose.yml up -d --build

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./.circleci/deploy/docker-push.sh
              ./.circleci/deploy/docker-push.sh
              chmod +x ./.circleci/deploy/docker-deploy.sh
              ./.circleci/deploy/docker-deploy.sh
            fi