// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/season/season.proto

package statistico_data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Season struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrent            *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Season) Reset()         { *m = Season{} }
func (m *Season) String() string { return proto.CompactTextString(m) }
func (*Season) ProtoMessage()    {}
func (*Season) Descriptor() ([]byte, []int) {
	return fileDescriptor_season_fdcdc5654278f517, []int{0}
}
func (m *Season) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Season.Unmarshal(m, b)
}
func (m *Season) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Season.Marshal(b, m, deterministic)
}
func (dst *Season) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Season.Merge(dst, src)
}
func (m *Season) XXX_Size() int {
	return xxx_messageInfo_Season.Size(m)
}
func (m *Season) XXX_DiscardUnknown() {
	xxx_messageInfo_Season.DiscardUnknown(m)
}

var xxx_messageInfo_Season proto.InternalMessageInfo

func (m *Season) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Season) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Season) GetIsCurrent() *wrappers.BoolValue {
	if m != nil {
		return m.IsCurrent
	}
	return nil
}

func init() {
	proto.RegisterType((*Season)(nil), "statistico_data.Season")
}

func init() { proto.RegisterFile("proto/season/season.proto", fileDescriptor_season_fdcdc5654278f517) }

var fileDescriptor_season_fdcdc5654278f517 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8d, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0x59, 0x0d, 0xc1, 0x0d, 0x0a, 0xf6, 0x64, 0x1e, 0x42, 0x3a, 0x79, 0x5a, 0xa1, 0x4e,
	0x5d, 0xeb, 0x0d, 0x0c, 0xba, 0xca, 0xa8, 0x9b, 0x0c, 0x98, 0x23, 0x3b, 0x23, 0xbd, 0x7e, 0xb0,
	0xd6, 0x69, 0x86, 0xf9, 0xe6, 0xff, 0x3f, 0x7d, 0x98, 0x3d, 0x09, 0x55, 0xec, 0x80, 0x69, 0xfa,
	0x0d, 0x1b, 0x6e, 0x66, 0xcf, 0x02, 0x82, 0x2c, 0xd8, 0x51, 0xd3, 0x83, 0x40, 0x7e, 0x1c, 0x88,
	0x86, 0xd1, 0x55, 0x01, 0xb7, 0xcb, 0xab, 0xfa, 0x78, 0x98, 0x67, 0xe7, 0x79, 0x0d, 0x9c, 0x06,
	0x9d, 0x3c, 0x42, 0x81, 0xd9, 0xe9, 0x08, 0xfb, 0x4c, 0x15, 0xaa, 0x8c, 0xeb, 0x08, 0x7b, 0x63,
	0xf4, 0x66, 0x82, 0xb7, 0xcb, 0xa2, 0x42, 0x95, 0x69, 0x1d, 0x76, 0x73, 0xd5, 0x1a, 0xb9, 0xe9,
	0x16, 0xef, 0xdd, 0x24, 0x59, 0x5c, 0xa8, 0x72, 0x7b, 0xce, 0xed, 0xaa, 0xb0, 0x7f, 0x85, 0xbd,
	0x11, 0x8d, 0x4f, 0x18, 0x17, 0x57, 0xa7, 0xc8, 0xf7, 0xf5, 0xb9, 0x4d, 0x02, 0xbe, 0x7c, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0x86, 0x2c, 0xf1, 0xbd, 0x00, 0x00, 0x00,
}
