// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/fixture/fixture.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	round "github.com/statistico/statistico-data/internal/proto/round"
	season "github.com/statistico/statistico-data/internal/proto/season"
	team "github.com/statistico/statistico-data/internal/proto/team"
	venue "github.com/statistico/statistico-data/internal/proto/venue"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DateRangeRequest struct {
	// RFC3339 formatted string i.e. "2006-01-02T15:04:05Z07:00"
	DateFrom string `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateTo               string   `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateRangeRequest) Reset()         { *m = DateRangeRequest{} }
func (m *DateRangeRequest) String() string { return proto.CompactTextString(m) }
func (*DateRangeRequest) ProtoMessage()    {}
func (*DateRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d47c9e18c1fc6f7, []int{0}
}

func (m *DateRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateRangeRequest.Unmarshal(m, b)
}
func (m *DateRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateRangeRequest.Marshal(b, m, deterministic)
}
func (m *DateRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateRangeRequest.Merge(m, src)
}
func (m *DateRangeRequest) XXX_Size() int {
	return xxx_messageInfo_DateRangeRequest.Size(m)
}
func (m *DateRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DateRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DateRangeRequest proto.InternalMessageInfo

func (m *DateRangeRequest) GetDateFrom() string {
	if m != nil {
		return m.DateFrom
	}
	return ""
}

func (m *DateRangeRequest) GetDateTo() string {
	if m != nil {
		return m.DateTo
	}
	return ""
}

type FixtureRequest struct {
	// The ID of the Fixture to be retrieved
	FixtureId            int64    `protobuf:"varint,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixtureRequest) Reset()         { *m = FixtureRequest{} }
func (m *FixtureRequest) String() string { return proto.CompactTextString(m) }
func (*FixtureRequest) ProtoMessage()    {}
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d47c9e18c1fc6f7, []int{1}
}

func (m *FixtureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureRequest.Unmarshal(m, b)
}
func (m *FixtureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureRequest.Marshal(b, m, deterministic)
}
func (m *FixtureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureRequest.Merge(m, src)
}
func (m *FixtureRequest) XXX_Size() int {
	return xxx_messageInfo_FixtureRequest.Size(m)
}
func (m *FixtureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureRequest proto.InternalMessageInfo

func (m *FixtureRequest) GetFixtureId() int64 {
	if m != nil {
		return m.FixtureId
	}
	return 0
}

type Fixture struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Competition          *proto2.Competition `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	Season               *season.Season      `protobuf:"bytes,3,opt,name=season,proto3" json:"season,omitempty"`
	Round                *round.Round        `protobuf:"bytes,4,opt,name=round,proto3" json:"round,omitempty"`
	HomeTeam             *team.Team          `protobuf:"bytes,5,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             *team.Team          `protobuf:"bytes,6,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	Venue                *venue.Venue             `protobuf:"bytes,7,opt,name=venue,proto3" json:"venue,omitempty"`
	RefereeId            *wrappers.Int64Value     `protobuf:"bytes,8,opt,name=referee_id,json=refereeId,proto3" json:"referee_id,omitempty"`
	DateTime             int64                    `protobuf:"varint,9,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Fixture) Reset()         { *m = Fixture{} }
func (m *Fixture) String() string { return proto.CompactTextString(m) }
func (*Fixture) ProtoMessage()    {}
func (*Fixture) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d47c9e18c1fc6f7, []int{2}
}

func (m *Fixture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixture.Unmarshal(m, b)
}
func (m *Fixture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixture.Marshal(b, m, deterministic)
}
func (m *Fixture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixture.Merge(m, src)
}
func (m *Fixture) XXX_Size() int {
	return xxx_messageInfo_Fixture.Size(m)
}
func (m *Fixture) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixture.DiscardUnknown(m)
}

var xxx_messageInfo_Fixture proto.InternalMessageInfo

func (m *Fixture) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fixture) GetCompetition() *proto2.Competition {
	if m != nil {
		return m.Competition
	}
	return nil
}

func (m *Fixture) GetSeason() *season.Season {
	if m != nil {
		return m.Season
	}
	return nil
}

func (m *Fixture) GetRound() *round.Round {
	if m != nil {
		return m.Round
	}
	return nil
}

func (m *Fixture) GetHomeTeam() *team.Team {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *Fixture) GetAwayTeam() *team.Team {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

func (m *Fixture) GetVenue() *venue.Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *Fixture) GetRefereeId() *wrappers.Int64Value {
	if m != nil {
		return m.RefereeId
	}
	return nil
}

func (m *Fixture) GetDateTime() int64 {
	if m != nil {
		return m.DateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*DateRangeRequest)(nil), "fixture.DateRangeRequest")
	proto.RegisterType((*FixtureRequest)(nil), "fixture.FixtureRequest")
	proto.RegisterType((*Fixture)(nil), "fixture.Fixture")
}

func init() {
	proto.RegisterFile("internal/proto/fixture/fixture.proto", fileDescriptor_3d47c9e18c1fc6f7)
}

var fileDescriptor_3d47c9e18c1fc6f7 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0x9f, 0xa4, 0x4f, 0x5e, 0x3c, 0xad, 0xa2, 0x6a, 0x2f, 0x35, 0xa9, 0xa8, 0x2a, 0x0b,
	0x01, 0x07, 0xb0, 0x51, 0x41, 0x1c, 0x2a, 0x04, 0x52, 0xa9, 0x2a, 0x22, 0x71, 0xda, 0x46, 0x3d,
	0x70, 0x89, 0x36, 0xf1, 0x24, 0x5d, 0x29, 0xf6, 0x86, 0xf5, 0xb8, 0xa5, 0x1f, 0x82, 0xef, 0xca,
	0x47, 0x40, 0x3b, 0xbb, 0x09, 0x96, 0x79, 0xb9, 0x8c, 0x67, 0xe6, 0xff, 0xdb, 0x5d, 0xe9, 0x3f,
	0x63, 0x78, 0xa2, 0x4b, 0x42, 0x5b, 0xaa, 0x75, 0xb6, 0xb1, 0x86, 0x4c, 0xb6, 0xd4, 0xdf, 0xa8,
	0xb6, 0xb8, 0xfd, 0xa6, 0xdc, 0x15, 0x83, 0x50, 0x8e, 0x4f, 0x56, 0xc6, 0xac, 0xd6, 0xe8, 0xe1,
	0x79, 0xbd, 0xcc, 0xee, 0xad, 0xda, 0x6c, 0xd0, 0x56, 0x1e, 0x1c, 0xbf, 0x68, 0x5d, 0xb7, 0x30,
	0xc5, 0x06, 0x49, 0x93, 0x36, 0x65, 0x33, 0x0f, 0xf4, 0x69, 0x8b, 0xb6, 0xa6, 0x2e, 0x73, 0x1f,
	0x03, 0x91, 0xb4, 0x88, 0x0a, 0x55, 0x65, 0xca, 0xf0, 0x09, 0xcc, 0x49, 0x8b, 0x21, 0x54, 0x05,
	0x87, 0xbf, 0xbc, 0x72, 0x87, 0x65, 0x8d, 0x3e, 0x7a, 0x22, 0xf9, 0x04, 0x87, 0x97, 0x8a, 0x50,
	0xaa, 0x72, 0x85, 0x12, 0xbf, 0xd6, 0x58, 0x91, 0x38, 0x86, 0x28, 0x57, 0x84, 0xb3, 0xa5, 0x35,
	0x45, 0xdc, 0x39, 0xed, 0x3c, 0x8f, 0xe4, 0xd0, 0x35, 0xae, 0xac, 0x29, 0xc4, 0x11, 0x0c, 0x58,
	0x24, 0x13, 0x77, 0x59, 0xea, 0xbb, 0x72, 0x6a, 0x92, 0x0c, 0x46, 0x57, 0xde, 0xaa, 0xed, 0x3d,
	0x8f, 0x01, 0x82, 0x79, 0x33, 0x9d, 0xf3, 0x45, 0x7b, 0x32, 0x0a, 0x9d, 0x49, 0x9e, 0xfc, 0xe8,
	0xc2, 0x20, 0x9c, 0x10, 0x23, 0xe8, 0xee, 0x90, 0xae, 0xce, 0xc5, 0x39, 0xec, 0x37, 0x3c, 0xe3,
	0x97, 0xf6, 0xcf, 0xe2, 0xb4, 0xe9, 0xe3, 0xc7, 0x5f, 0xb9, 0x6c, 0xc2, 0xe2, 0x29, 0xf4, 0xbd,
	0x49, 0xf1, 0x1e, 0x1f, 0x1b, 0xa5, 0xc1, 0xb3, 0x6b, 0xfe, 0xc8, 0xa0, 0x8a, 0x04, 0x7a, 0xec,
	0x77, 0xfc, 0x3f, 0x63, 0x07, 0xa9, 0x77, 0x5f, 0xba, 0x28, 0xbd, 0x24, 0x9e, 0x41, 0x74, 0x6b,
	0x0a, 0x9c, 0x39, 0x4f, 0xe3, 0x1e, 0x73, 0x90, 0xb2, 0xc1, 0x53, 0x54, 0x85, 0x1c, 0x3a, 0xd1,
	0x65, 0x0e, 0x54, 0xf7, 0xea, 0xc1, 0x83, 0xfd, 0xdf, 0x41, 0x27, 0x32, 0x98, 0x40, 0x8f, 0xfd,
	0x8f, 0x07, 0xe1, 0x55, 0x3f, 0x8d, 0x1b, 0x17, 0xa5, 0x97, 0xc4, 0x39, 0x80, 0xc5, 0x25, 0x5a,
	0x64, 0xe3, 0x86, 0x0c, 0x1e, 0xa7, 0x7e, 0xff, 0xd2, 0xed, 0xfe, 0xa5, 0x93, 0x92, 0xde, 0xbe,
	0xb9, 0x51, 0xeb, 0x1a, 0x65, 0x14, 0xf0, 0x49, 0xbe, 0x1b, 0x1e, 0xe9, 0x02, 0xe3, 0x88, 0x0d,
	0xe5, 0xe1, 0x4d, 0x75, 0x81, 0x67, 0xdf, 0x3b, 0xbb, 0x21, 0x5d, 0xa3, 0xbd, 0xd3, 0x0b, 0x14,
	0x1f, 0xe0, 0xe0, 0xb3, 0xae, 0x28, 0x74, 0x2b, 0xf1, 0x28, 0xdd, 0xee, 0x7f, 0x7b, 0x2f, 0xc6,
	0x87, 0x3b, 0x29, 0xd0, 0xc9, 0x7f, 0xaf, 0x3a, 0x6e, 0x54, 0xa1, 0xbc, 0x78, 0x98, 0x5c, 0x8a,
	0xa3, 0x36, 0xf4, 0x8f, 0xd3, 0x17, 0xef, 0xbf, 0xbc, 0x5b, 0x69, 0xba, 0xad, 0xe7, 0x6e, 0xb2,
	0x59, 0x45, 0x8a, 0x74, 0x45, 0x7a, 0x61, 0x1a, 0xe9, 0xcb, 0x5c, 0x91, 0xca, 0xfe, 0xfc, 0xab,
	0xce, 0xfb, 0x5c, 0xbe, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x33, 0xb5, 0x7b, 0xcc, 0xcb, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FixtureServiceClient is the client API for FixtureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FixtureServiceClient interface {
	ListFixtures(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (FixtureService_ListFixturesClient, error)
	FixtureByID(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*Fixture, error)
}

type fixtureServiceClient struct {
	cc *grpc.ClientConn
}

func NewFixtureServiceClient(cc *grpc.ClientConn) FixtureServiceClient {
	return &fixtureServiceClient{cc}
}

func (c *fixtureServiceClient) ListFixtures(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (FixtureService_ListFixturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FixtureService_serviceDesc.Streams[0], "/fixture.FixtureService/ListFixtures", opts...)
	if err != nil {
		return nil, err
	}
	x := &fixtureServiceListFixturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FixtureService_ListFixturesClient interface {
	Recv() (*Fixture, error)
	grpc.ClientStream
}

type fixtureServiceListFixturesClient struct {
	grpc.ClientStream
}

func (x *fixtureServiceListFixturesClient) Recv() (*Fixture, error) {
	m := new(Fixture)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fixtureServiceClient) FixtureByID(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*Fixture, error) {
	out := new(Fixture)
	err := c.cc.Invoke(ctx, "/fixture.FixtureService/FixtureByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixtureServiceServer is the server API for FixtureService service.
type FixtureServiceServer interface {
	ListFixtures(*DateRangeRequest, FixtureService_ListFixturesServer) error
	FixtureByID(context.Context, *FixtureRequest) (*Fixture, error)
}

// UnimplementedFixtureServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFixtureServiceServer struct {
}

func (*UnimplementedFixtureServiceServer) ListFixtures(req *DateRangeRequest, srv FixtureService_ListFixturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFixtures not implemented")
}
func (*UnimplementedFixtureServiceServer) FixtureByID(ctx context.Context, req *FixtureRequest) (*Fixture, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FixtureByID not implemented")
}

func RegisterFixtureServiceServer(s *grpc.Server, srv FixtureServiceServer) {
	s.RegisterService(&_FixtureService_serviceDesc, srv)
}

func _FixtureService_ListFixtures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DateRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FixtureServiceServer).ListFixtures(m, &fixtureServiceListFixturesServer{stream})
}

type FixtureService_ListFixturesServer interface {
	Send(*Fixture) error
	grpc.ServerStream
}

type fixtureServiceListFixturesServer struct {
	grpc.ServerStream
}

func (x *fixtureServiceListFixturesServer) Send(m *Fixture) error {
	return x.ServerStream.SendMsg(m)
}

func _FixtureService_FixtureByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServiceServer).FixtureByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fixture.FixtureService/FixtureByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServiceServer).FixtureByID(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FixtureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fixture.FixtureService",
	HandlerType: (*FixtureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FixtureByID",
			Handler:    _FixtureService_FixtureByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFixtures",
			Handler:       _FixtureService_ListFixtures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/fixture/fixture.proto",
}
