// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/proto/round.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Round struct {
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SeasonId int64  `protobuf:"varint,3,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	StartDate string `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	EndDate              string   `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e24a3a92546951b, []int{0}
}

func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (m *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(m, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Round) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Round) GetSeasonId() int64 {
	if m != nil {
		return m.SeasonId
	}
	return 0
}

func (m *Round) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Round) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func init() {
	proto.RegisterType((*Round)(nil), "proto.Round")
}

func init() { proto.RegisterFile("internal/app/proto/round.proto", fileDescriptor_3e24a3a92546951b) }

var fileDescriptor_3e24a3a92546951b = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8e, 0xbd, 0x0a, 0xc2, 0x40,
	0x0c, 0x80, 0xb9, 0xfe, 0x68, 0x9b, 0xc1, 0x21, 0xd3, 0x89, 0x28, 0xc5, 0xa9, 0x93, 0x1d, 0x7c,
	0x05, 0x17, 0xd7, 0xbe, 0x40, 0x89, 0x24, 0xc3, 0x81, 0xe6, 0xca, 0xf5, 0x7c, 0x01, 0x9f, 0x5c,
	0x9a, 0x4e, 0xf9, 0xf8, 0xbe, 0x04, 0x02, 0x97, 0xa0, 0x59, 0x92, 0xd2, 0x7b, 0xa0, 0x79, 0x1e,
	0xe6, 0x14, 0x73, 0x1c, 0x52, 0xfc, 0x2a, 0xdf, 0x8c, 0xb1, 0xb6, 0x71, 0xfd, 0x39, 0xa8, 0xc7,
	0x55, 0xe3, 0x01, 0x8a, 0xc0, 0xde, 0x75, 0xae, 0x2f, 0xc7, 0x22, 0x30, 0x22, 0x54, 0x4a, 0x1f,
	0xf1, 0x45, 0xe7, 0xfa, 0x76, 0x34, 0xc6, 0x13, 0xb4, 0x8b, 0xd0, 0x12, 0x75, 0x0a, 0xec, 0x4b,
	0x5b, 0x6d, 0x36, 0xf1, 0x64, 0x3c, 0x03, 0x2c, 0x99, 0x52, 0x9e, 0x98, 0xb2, 0xf8, 0xca, 0xce,
	0x5a, 0x33, 0x0f, 0xca, 0x82, 0x47, 0x68, 0x44, 0x79, 0x8b, 0xb5, 0xc5, 0xbd, 0x28, 0xaf, 0xe9,
	0xb5, 0xb3, 0x5f, 0xee, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x7a, 0x58, 0x8b, 0xb4, 0x00,
	0x00, 0x00,
}
