// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/proto/season.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Season struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrent            *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Season) Reset()         { *m = Season{} }
func (m *Season) String() string { return proto.CompactTextString(m) }
func (*Season) ProtoMessage()    {}
func (*Season) Descriptor() ([]byte, []int) {
	return fileDescriptor_2903670fe0606efc, []int{0}
}

func (m *Season) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Season.Unmarshal(m, b)
}
func (m *Season) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Season.Marshal(b, m, deterministic)
}
func (m *Season) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Season.Merge(m, src)
}
func (m *Season) XXX_Size() int {
	return xxx_messageInfo_Season.Size(m)
}
func (m *Season) XXX_DiscardUnknown() {
	xxx_messageInfo_Season.DiscardUnknown(m)
}

var xxx_messageInfo_Season proto.InternalMessageInfo

func (m *Season) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Season) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Season) GetIsCurrent() *wrappers.BoolValue {
	if m != nil {
		return m.IsCurrent
	}
	return nil
}

func init() {
	proto.RegisterType((*Season)(nil), "proto.Season")
}

func init() { proto.RegisterFile("internal/app/proto/season.proto", fileDescriptor_2903670fe0606efc) }

var fileDescriptor_2903670fe0606efc = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8d, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0x49, 0xfb, 0x7d, 0x85, 0x46, 0x70, 0xc8, 0x54, 0x3a, 0x68, 0x71, 0xea, 0x94, 0x80,
	0x4e, 0xae, 0xfa, 0x0f, 0x2a, 0xb8, 0xca, 0xd5, 0x9e, 0x25, 0x10, 0x73, 0xe1, 0xd2, 0xe2, 0xdf,
	0x17, 0x12, 0x9c, 0xee, 0x5e, 0xde, 0xe7, 0xe5, 0x91, 0x7b, 0xeb, 0x17, 0x64, 0x0f, 0xce, 0x40,
	0x08, 0x26, 0x30, 0x2d, 0x64, 0x22, 0x42, 0x24, 0xaf, 0x53, 0x50, 0xff, 0xe9, 0xb4, 0xbb, 0x99,
	0x68, 0x76, 0x98, 0x89, 0x71, 0x7d, 0x99, 0x0f, 0x43, 0x08, 0xc8, 0x31, 0x63, 0x87, 0x59, 0x56,
	0xb7, 0x34, 0x53, 0x5b, 0x59, 0xd8, 0xa9, 0x11, 0x9d, 0xe8, 0xcb, 0xa1, 0xb0, 0x93, 0x52, 0xf2,
	0xcf, 0xc3, 0x1b, 0x9b, 0xa2, 0x13, 0x7d, 0x3d, 0xa4, 0x5f, 0x9d, 0xa5, 0xb4, 0xf1, 0xf1, 0x5c,
	0x99, 0xd1, 0x2f, 0x4d, 0xd9, 0x89, 0x7e, 0x73, 0x6c, 0x75, 0x56, 0xe8, 0x9f, 0x42, 0x5f, 0x88,
	0xdc, 0x1d, 0xdc, 0x8a, 0x43, 0x6d, 0xe3, 0x35, 0xc3, 0x63, 0x95, 0xea, 0xd3, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x25, 0xd0, 0x32, 0xfc, 0xb9, 0x00, 0x00, 0x00,
}
