// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/competition/competition.proto

package competition // import "github.com/statistico/statistico-data/internal/proto/competition"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Competition struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCup                *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_cup,json=isCup,proto3" json:"is_cup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Competition) Reset()         { *m = Competition{} }
func (m *Competition) String() string { return proto.CompactTextString(m) }
func (*Competition) ProtoMessage()    {}
func (*Competition) Descriptor() ([]byte, []int) {
	return fileDescriptor_competition_3b58bdd4aba1d168, []int{0}
}
func (m *Competition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Competition.Unmarshal(m, b)
}
func (m *Competition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Competition.Marshal(b, m, deterministic)
}
func (dst *Competition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Competition.Merge(dst, src)
}
func (m *Competition) XXX_Size() int {
	return xxx_messageInfo_Competition.Size(m)
}
func (m *Competition) XXX_DiscardUnknown() {
	xxx_messageInfo_Competition.DiscardUnknown(m)
}

var xxx_messageInfo_Competition proto.InternalMessageInfo

func (m *Competition) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Competition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Competition) GetIsCup() *wrappers.BoolValue {
	if m != nil {
		return m.IsCup
	}
	return nil
}

func init() {
	proto.RegisterType((*Competition)(nil), "competition.Competition")
}

func init() {
	proto.RegisterFile("internal/proto/competition/competition.proto", fileDescriptor_competition_3b58bdd4aba1d168)
}

var fileDescriptor_competition_3b58bdd4aba1d168 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x85, 0x49, 0x7f, 0x2d, 0x98, 0x82, 0x43, 0xa6, 0xd2, 0x41, 0x8a, 0x53, 0x07, 0x4d, 0x50,
	0x5f, 0x40, 0xda, 0x37, 0xe8, 0xe0, 0xe0, 0x22, 0x69, 0x12, 0xeb, 0x85, 0x34, 0x37, 0x24, 0x37,
	0xf8, 0xfa, 0x42, 0x8b, 0xd8, 0xc5, 0xed, 0xe3, 0xdc, 0x73, 0xf9, 0x38, 0xfc, 0x01, 0x02, 0xb9,
	0x14, 0xb4, 0x57, 0x31, 0x21, 0xa1, 0x32, 0xb8, 0x45, 0x47, 0x40, 0x80, 0xe1, 0xcc, 0x72, 0xbf,
	0x8a, 0xe6, 0x14, 0x75, 0x77, 0x2b, 0xe2, 0xea, 0xdd, 0xf1, 0xb8, 0x94, 0x4f, 0xf5, 0x9d, 0x74,
	0x8c, 0x2e, 0xe5, 0xa3, 0x7c, 0x6f, 0x79, 0x33, 0xfd, 0xd5, 0xc5, 0x2d, 0xaf, 0xc0, 0xb6, 0xac,
	0x67, 0xc3, 0x65, 0xae, 0xc0, 0x0a, 0xc1, 0xaf, 0x82, 0xde, 0x5c, 0x5b, 0xf5, 0x6c, 0xb8, 0x99,
	0x77, 0x16, 0x4f, 0xbc, 0x86, 0xfc, 0x61, 0x4a, 0x6c, 0x2f, 0x3d, 0x1b, 0x9a, 0xe7, 0x4e, 0x1e,
	0x0e, 0xf9, 0xeb, 0x90, 0x23, 0xa2, 0x7f, 0xd3, 0xbe, 0xb8, 0xf9, 0x1a, 0xf2, 0x54, 0xe2, 0x38,
	0xbe, 0xbf, 0xae, 0x40, 0x5f, 0x65, 0x91, 0x06, 0x37, 0x95, 0x49, 0x13, 0x64, 0x02, 0x83, 0x27,
	0x7c, 0xb4, 0x9a, 0xb4, 0xfa, 0x7f, 0xe8, 0x52, 0xef, 0xd1, 0xcb, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x91, 0x52, 0x81, 0xde, 0x0d, 0x01, 0x00, 0x00,
}
